apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-static-volume
  labels:
    name: web
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /var/www/html
          name: web-volume
  volumes:
    - name: web-volume
      persistentVolumeClaim:
        claimName: static-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume-claim
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      role: pd
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-volume
  namespace: default
  labels:
    role: pd
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  gcePersistentDisk:
    pdName: web-volume
    fsType: "ext4"
