apiVersion: v1
kind: Pod
metadata:
  name: "wordpress"
  namespace: default
  labels:
    app: "wordpress"
spec:
  volumes:
    - name: wordpress-sql-credential
      secret:
        secretName: wordpress-sql-proxy
  containers:
    - name: wordpress
      image: wordpress:5.2.3-php7.1-apache
      env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: password
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_TABLE_PREFIX
          value: wp
      ports:
        - containerPort: 80
          # name: http
    - name: cloud-sql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.12
      command: 
        - "/cloud_sql_proxy"
        - "-instances=work-999999:asia-northeast1:wordpress=tcp:3306"
        - "-credential_file=/home/root/credential.json"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: wordpress-sql-credential
          mountPath: /home/root

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: default
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
